
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://host.docker.internal:8761/eureka}
  instance:
     hostname: host.docker.internal
